### ISSUE TITLE
Epic: Automated log and data collection

### ISSUE THREAD

**Issue by vthapar** [submariner-io/submariner-operator#1125]
This will track tasks needed to fully automate collection of data and logs to troubleshoot any submariner issues in deployments.

- [x] Add `subctl` sub-command to gather logs and data from a specific cluster #1152 
- [x] Add an option to gather data sub-command to gather data from all clusters #1218 
- [x] Generate tarball with all the gathered data
- [ ] Modify gather data sub-command to selectively collect logs and data based on related failures
- [x] Capture logs from submariner-operator pods #1143 
- [x] Capture logs from all submariner/connectivity pods #1143
- [x] Capture logs from all service discovery pods #1143
- [x] Capture all data present on broker #1154
- [x] Capture data from operator and related config CRs #1155 
- [x] Capture data from submariner/connectivity resources like Clusters, Gateways, configmaps etc. #1156 
- [x] Capture data from service discovery resources like ServiceExports/Imports, Endpointslices, configmaps etc. #1158 
- [x] Capture data specific to CNI/CableDriver specific #1157 
- [ ] Add `subctl` sub-command to change debug verbosity level for specific pods before gathering data
- [x] Add e2e tests for the new `subctl` gather command #1194
- [x] Add log file to include additional info of note during the collection process, eg how many resources of a type were collected.

**Comment by Jaanki** [comment]
I am taking tasks 5,6 and 7 to collect logs from submariner and related pods. Raised a issue https://github.com/submariner-io/submariner-operator/issues/1143

**Comment by Jaanki** [comment]
https://github.com/submariner-io/submariner-operator/pull/1188
