### ISSUE TITLE
Epic: Subctl diagnostic tool to validate the Submariner deployment

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner-operator#1126]
**What would you like to be added**:

Currently, after joining clusters with Submariner, we have a provision to run the "subctl verify ..." command.
This command triggers various end-to-end tests and displays the results. In case of any test failure, we will only know the scenario that failed but will have to debug from the logs on why the test-case failed.

It would be great if subctl can be enhanced to validate the infrastructure/deployment and report any issues.

The tool can validate the following

- [x] 1. [Verify that all the Submariner Pods (expected configuration can be read from the Submariner CR) are in Running state.](https://github.com/submariner-io/submariner-operator/issues/1141) 
- [x] 2. [Verify if the NETWORK_PLUGIN is supported by Submariner.](https://github.com/submariner-io/submariner-operator/issues/1138)
- [x] 3. [Verify if the Kubernetes version is supported.](https://github.com/submariner-io/submariner-operator/issues/1138)
- [x] 4. [Verify stale endpoints and overlapping issues in a deployment.](https://github.com/submariner-io/submariner-operator/issues/1144)
- [x] 5. [Verify if the gateway connections are properly established.](https://github.com/submariner-io/submariner-operator/issues/1145)
- [x] 6. [Verify if firewall configuration allows UDP/4800 port between all the nodes in the cluster.](https://github.com/submariner-io/submariner-operator/issues/1146)
- [x] 7. [Verify if firewall configuration allows ingress UDP 4500/500 on the Gateway nodes.](https://github.com/submariner-io/submariner-operator/issues/1147)
- [x] 8. [Verify if firewall configuration allows ingress TCP 8080 on the Gateway nodes.](https://github.com/submariner-io/submariner-operator/issues/1148)
- [x] 9. [If using Calico CNI, ensure that necessary Calico IPPools are created.](https://github.com/submariner-io/submariner-operator/issues/1149)
- [x] 10. [Verify that Cluster is deployed with kube-proxy IPtables driver.](https://github.com/submariner-io/submariner-operator/issues/1150)
- [x] 11. [Verify if any of the Submariner pods are constantly restarting.](https://github.com/submariner-io/submariner-operator/issues/1151)
- [x] 12 [Support subctl validate all](https://github.com/submariner-io/submariner-operator/pull/1256)
- [x] 13. [Document the corresponding changes in website.](https://github.com/submariner-io/submariner-website/issues/461)

**Why is this needed**:
It will automate the debugging process and reduce the manual intervention.

**Comment by nyechiel** [comment]
All planned items seems to be completed at this point. If there are remaining gaps, we can track them outside of the epic.
