### ISSUE TITLE
subctl should be refactored to a library, and make subctl the CLI of that library

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner-operator#1329]
**What would you like to be added**:

Splitting subctl in two parts, an interface part, and a library part, the library would contain all the logic
that subctl uses, and a defined Interface that external projects can consume

**Why is this needed**:

In this way, other projects can use the subctl logic to deploy clusters and brokers in an automated
way without calling the subctl logic from the command line.

**Work items:**
- [x] Rename apis -> api
    - [x] Depends on https://github.com/submariner-io/submariner-operator/pull/1651
    - [x] Depends on https://github.com/open-cluster-management/submariner-addon/pull/220
- [x] Move all cobra related stuff to cmd/subctl, Logic called by subctl inside pkg/cmd/subctl for below commands
    - [x] deploy-broker Depends on https://github.com/submariner-io/submariner-operator/pull/1663
    - [x] join Depends on https://github.com/submariner-io/submariner-operator/pull/1726
    - [x] benchmark Depends on https://github.com/submariner-io/submariner-operator/pull/1772
    - [x] verify Depends on https://github.com/submariner-io/submariner-operator/pull/1795
    - [x] version Depends on https://github.com/submariner-io/submariner-operator/pull/1663 
    - [x] diagnose
      - [x] Depends on https://github.com/submariner-io/submariner-operator/pull/1994
      - [x] Depends on https://github.com/submariner-io/submariner-operator/pull/2015
    - [x] show
      - [x] Changes made in [Print out brokers information on subctl show all](https://github.com/submariner-io/submariner-operator/pull/1924/files#)
      - [x] Depends on https://github.com/submariner-io/submariner-operator/pull/2006
    - [x] gather
      - [x] Depends on https://github.com/submariner-io/submariner-operator/pull/1801
      - [x] Depends on https://github.com/submariner-io/submariner-operator/pull/2007
      - [x] Depends on https://github.com/submariner-io/submariner-operator/pull/2043
    - [x] cloud 
      - [x] Depends on https://github.com/submariner-io/submariner-operator/pull/1770
      - [x] Depends on https://github.com/submariner-io/submariner-operator/pull/2013
      - [x] Depends on https://github.com/submariner-io/submariner-operator/pull/2041
      - [x] Depends on https://github.com/submariner-io/submariner-operator/pull/2049
      - [x] Depends on https://github.com/submariner-io/submariner-operator/pull/2048
      - [x] Move all cobra stuff to cmd/subctl/* Depends on https://github.com/submariner-io/submariner-operator/pull/2061
    - [x] export
      - [x] Depends on https://github.com/submariner-io/submariner-operator/pull/1817
    - [x] unexport 
      - [x] Depends on https://github.com/submariner-io/submariner-operator/pull/1983
    - [x] uninstall 
      - [x] Depends on https://github.com/submariner-io/submariner-operator/pull/1980
- [x] pkg/internal -> /internal Depends on https://github.com/submariner-io/submariner-operator/pull/1705
- [x] [Add a generic status handler to all commands](https://github.com/submariner-io/submariner-operator/pull/1663#discussion_r761949270) Depends on https://github.com/submariner-io/submariner-operator/pull/1705  
- [x] [Handle broker data storage in a more generic way rather than a file](https://github.com/submariner-io/submariner-operator/pull/1663#discussion_r761949733) Depends on https://github.com/submariner-io/submariner-operator/pull/1717
- [x] Move packages out of `pkg/subctl` 
    - [x] Depends on https://github.com/submariner-io/submariner-operator/pull/1800
    - [x] Depends on https://github.com/submariner-io/submariner-operator/pull/1799
    - [x] Depends on https://github.com/submariner-io/submariner-operator/pull/1761
- [x] Other optimisations
    - [x] Depends on https://github.com/submariner-io/submariner-operator/pull/1786
    - [x] Depends on https://github.com/submariner-io/submariner-operator/pull/1775
    - [x] Depends on https://github.com/submariner-io/submariner-operator/pull/1773
    - [x] Depends on https://github.com/submariner-io/submariner-operator/pull/1743
    - [x] Depends on https://github.com/submariner-io/submariner-operator/pull/1740
    - [x] Depends on https://github.com/submariner-io/submariner-operator/pull/1804
    - [x] Depends on https://github.com/submariner-io/submariner-operator/pull/1806
    - [x] Depends on: https://github.com/submariner-io/submariner-operator/pull/1735

Just few examples. Follow 
https://github.com/golang-standards/project-layout 
https://medium.com/golang-learn/go-project-layout-e5213cdcfaa2
https://vsoch.github.io/2019/go/

**Comment by mangelajo** [comment]
@mkolesnik ping ^

**Comment by mangelajo** [comment]
This would also be beneficial for testing because we could test subctl better by having good interfaces that we can mock.
