### ISSUE TITLE
Epic: Support OCP with submariner on AWS

### ISSUE THREAD

**Issue by vthapar** [submariner-io/submariner-operator#1530]
**What would you like to be added**:
Proposal is to fully support connecting multiple OCP clusters on AWS using Submariner.

**Why is this needed**:
Aim of this proposal is to list and track steps needed to fill any gaps and allow full support for such deployments.

**Work Items**

- [x] Deploy using cloud prepare and subctl on existing OCP clusters on AWS
- [x] Deploy using [OCM and submariner-addon](https://github.com/open-cluster-management/submariner-addon) on OCP clusters on AWS
- [x] Support and run subctl verify
- [x] Support and run subctl diagnose
- [x] Support and run subctl gather
- [x] Remove cluster from multcluster using subctl
- [x] Remove cluster from multicluster using OCM and submariner-addon
- [ ] Uninstall submariner using subctl
- [ ] Uninstall submariner using OCM and submariner-addon
- [ ] UI support for troubleshooting etc. on OCM
- [x] Documentation for deployments and removal using cloud-prepare and subctl
- [ ] Documentation for deployments and removal using OCM

**Comment by nyechiel** [comment]
@vthapar can this be closed at this point? I think that this is done besides the uninstallation flow which will need to be addressed separately in 0.12.

**Comment by vthapar** [comment]
Uninstallation and debuggability tracked by separate EPICs, so closing this one.

https://github.com/submariner-io/enhancements/issues/50

submariner-io/enhancements#88
