### ISSUE TITLE
Epic: Support OCP with submariner on GCP

### ISSUE THREAD

**Issue by vthapar** [submariner-io/submariner-operator#1531]
**What would you like to be added**:
Proposal is to fully support connecting multiple OCP clusters on GCP using Submariner.

**Why is this needed**:
Aim of this proposal is to list and track steps needed to fill any gaps and allow full support for such deployments.

**Work Items**

- [x] Deploy using cloud prepare and subctl on existing OCP clusters on GCP
- [x] [Enhance cloud-prepare to support deploying dedicated Gateway nodes on GCP](https://github.com/submariner-io/cloud-prepare/pull/92)
- [x] [Enhance cloud-prepare to support configuring existing worker nodes as GW nodes on GCP](https://github.com/submariner-io/cloud-prepare/pull/97)
- [x] Deploy using [OCM and submariner-addon](https://github.com/open-cluster-management/submariner-addon) on OCP clusters on GCP (https://github.com/open-cluster-management/submariner-addon/issues/115)
- [x] Support and run subctl verify
- [x] Support and run subctl diagnose
- [x] Support and run subctl gather
- [ ] Remove cluster from multcluster using subctl
- [ ] Remove cluster from multicluster using OCM and submariner-addon
- [ ] Uninstall submariner using subctl
- [ ] Uninstall submariner using OCM and submariner-addon
- [ ] UI support for troubleshooting etc. on OCM
- [ ] Documentation for deployments and removal using cloud-prepare and subctl
- [ ] Documentation for deployments and removal using OCM

**Comment by sridhargaddam** [comment]
The following PR supports configuring dedicated Gateway nodes on GCP - https://github.com/submariner-io/cloud-prepare/pull/92

**Comment by nyechiel** [comment]
@sridhargaddam @aswinsuryan can this be closed at this point? I think that this is done besides the uninstallation flow which will need to be addressed separately in 0.12.
