### ISSUE TITLE
Epic: Support OCP with submariner on Azure

### ISSUE THREAD

**Issue by vthapar** [submariner-io/submariner-operator#1532]
**What would you like to be added**:
Proposal is to fully support connecting multiple OCP clusters on Azure using Submariner.

**Why is this needed**:
Aim of this proposal is to list and track steps needed to fill any gaps and allow full support for such deployments.

**Work Items**

- [ ] Deploy using cloud prepare and subctl on existing OCP clusters on Azure
- [ ] Deploy using [OCM and submariner-addon](https://github.com/open-cluster-management/submariner-addon) on OCP clusters on AWS
- [ ] Support and run subctl verify
- [ ] Support and run subctl diagnose
- [ ] Support and run subctl gather
- [ ] Remove cluster from multcluster using subctl
- [ ] Remove cluster from multicluster using OCM and submariner-addon
- [ ] Uninstall submariner using subctl
- [ ] Uninstall submariner using OCM and submariner-addon
- [ ] UI support for troubleshooting etc. on OCM
- [ ] Documentation for deployments and removal using cloud-prepare and subctl
- [ ] Documentation for deployments and removal using OCM

**Comment by dfarrell07** [comment]
Should we move this epic to the enhancements repo?
