### ISSUE TITLE
[EPIC] Restructure/refactor submariner-operator repo

### ISSUE THREAD

**Issue by Jaanki** [submariner-io/submariner-operator#1634]
- [x] Move packaging of operator to another repo - "`deploy`"?
- [x] Make subctl a library - Depends on https://github.com/submariner-io/submariner-operator/issues/1329
- [x] Support to install operator in custom namespace -  Deepnds on https://github.com/submariner-io/submariner-operator/issues/1040
- [x] Use `go:embed` instead of `go:generate`
- [x] Check for any other optimizations

**Comment by Jaanki** [comment]
[Note for self] Support for the legacy package manifest format for Operators is removed in OpenShift Container Platform 4.8 and later.

**Comment by Jaanki** [comment]
Closed in favor of https://github.com/submariner-io/enhancements/issues/53
