### ISSUE TITLE
Debuggability and troubleshootig

### ISSUE THREAD

**Issue by vthapar** [submariner-io/submariner-operator#1649]
---
name: Debuggability and Troubleshooting
about: Improving debuggability and troubleshooting for submariner deplyments in general, OCM in particular
labels: epic

---
## Epic Description
Current documentation on Sumariner.io - (Troubleshooting docs)[https://submariner.io/operations/troubleshooting/] covers the basic manual steps and how to run subctl diagnose and gather. What more needs to be done? Aim is to make it easy for support teams to troubleshoot and resolve the problems, or capture relevant information if unable to resolve.

## Acceptance Criteria
TBD

## Definition of Done (Checklist)

* [ ] Code complete
* [ ] Relevant metrics added
* [ ] The acceptance criteria met
* [ ] Unit/e2e test added & pass
* [ ] CI jobs pass
* [ ] Deployed using cloud-prepare+subctl
* [ ] Deployed using ACM/OCM addon
* [ ] Deploy using Helm
* [ ] Deployed on supported platforms (for e.g kind, OCP on AWS, OCP on GCP)
* [ ] Run subctl verify, diagnose and gather
* [ ] Uninstall
* [ ] Troubleshooting (gather/diagnose) added
* [ ] Documentation added
* [ ] Release notes added

## Work Items
* [ ] Documentation - Add missing options in `subctl diagnose`
* [ ] Documentation - Add information on how to interpret `diagnose` output
* [ ] Documentation - Add more information on different `subctl gather` options
* [ ] Documentation - Add information on specific gather data to look at for different issues discovered by `diagnose`
* [ ] Documentation - Add manual troubleshooting steps for anything not covered by `diagnose`
* [ ] Documentation - More verbose output form `gather` and `diagnose`
* [ ] `subctl` - Handle multiple kubeconfigs/contexts better, avoid gathering information from same cluster repeatedly
* [ ] `diagnose` -  Detect errors in cloud deployment
* [ ] `diagnose` -  Detect service discovery issues
* [ ] `diagnose` -  Detect cabledriver issues
* [ ] `gather` -  Gather logs from `submariner-addon` if OCM deployment
* [ ] `gather` -  Gather information from cloud e.g. ports opened etc.
* [ ] OCM - Refactor `subctl` code to reuse `gather` and `dianose` like a library
* [ ] OCM - Run `gather` from a container/host on cluster and pull logs [subctl collects logs on host where subctl is run]
* [ ] OCM - Add troubleshooting options to existing OCM UI
* [ ] OCP `must-gather` - Add `gather` to [OCP must-gather](https://github.com/openshift/must-gather)
* [ ] CI/CD - Add `subctl diagnose` to CI/CD in case of any test failure
* [ ] CI/CD - Use `subctl gather` in CI/CD post-mortem in case of any test failure
* [ ] CI/CD - Identify nature of failure in CI/CD to run subset of diagnose/gather and collect minimal information required.

**Comment by dfarrell07** [comment]
I can help with the CI/CD work items you have listed there if you'd like, @vthapar.

**Comment by dfarrell07** [comment]
Do we want to move this epic to the enhancements repo?

**Comment by vthapar** [comment]
Partialy done in 2.5. All UI items were scoped out of 2.5 due to other higher priority work items with UI team.
