### ISSUE TITLE
Epic: Plan to improve Submariner deployment

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner-operator#695]
A number of development efforts are currently ongoing to improve Submariner deployments; this issue attempts to track them all, explain the overall narrative and identify dependencies.

- [x] **(Done)** CRD handling: CRDs are currently defined in a number of projects, because they are all handled externally; this includes the operator, the Helm charts, and the CSV. To fix that, as many as possible are being migrated to in-operator handling, see https://github.com/submariner-io/submariner-operator/issues/686. This will also allow the operator to take care of CRD upgrades.
- [x] **(In progress for v0.7)** Helm operator deployment: this has been on the backlog for a long time, see https://github.com/submariner-io/submariner-charts/issues/17. With CRDs handled in the operator, the Helm charts will be greatly simplified. We’ll probably end up with three: one to deploy the operator, one to deploy the broker (directly or using the operator), and one to deploy Submariner using the operator. (This requires the Submariner release to be tagged, so while this targets 0.7 it will only happen after the 0.7 release.)
- [x] **(v0.8)** Migrating to the Operator SDK v1: see https://github.com/submariner-io/submariner-operator/issues/678.
- [x] **(v0.8)** Migrating CRDs to v1: K8s 1.19 will obsolete v1beta1 CRDs, so we need to migrate to v1. This should be easier once we’ve migrated to v1 of the Operator SDK; the CRDs should be generatable from the types’ source then. See https://github.com/submariner-io/submariner-operator/issues/747
- [x] **(v0.9)** Use the operator-based Helm chart for deployments by default; see https://github.com/submariner-io/shipyard/pull/356 (which was reverted).
- [ ] **(v0.9)** If appropriate, merge the Terraform script: see https://github.com/submariner-io/submariner/issues/873
- [x] **(v0.9)** Handling the broker in the operator. This is desirable _e.g._ for ACM. See https://github.com/submariner-io/submariner-operator/issues/203.
- [x] **(v0.9)** SA and RBAC handling: it seems dangerous to give the operator sufficient permissions to handle SAs and RBAC, so we’ll leave that to `subctl` and other orchestrators. However the RBAC descriptors should be generated from code using Kubebuilder (in the Operator SDK), so that their utility can be determined more easily. See also https://github.com/submariner-io/submariner-operator/issues/679.
- [x] Migrating to Helm v3: this should only be done once the Helm charts have been cleaned up to match the operator. See https://github.com/submariner-io/submariner-charts/issues/47. This also requires v1 CRDs.
- [x] Migrate submariner-charts repo to GHA from Tavis, clean up CI.

**Comment by nyechiel** [comment]
this is work in progress dear bot

**Comment by nyechiel** [comment]
This one is pretty much done, and I don't think we have a need to keep it open anymore.
