### ISSUE TITLE
Epic: Handle upgrades

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner-operator#746]
This will track issues encountered when dealing with upgrades (see https://github.com/submariner-io/submariner-operator/pull/711), *only for 0.8* (_i.e._ upgrades from 0.7 to 0.8).

* [x] Deleting the Submariner CR doesn’t remove any deployments: https://github.com/submariner-io/submariner-operator/issues/749
* [x] Deleting the ServiceDiscovery CR doesn’t delete the corresponding deployments: #753
* [x] Deleting the Submariner CR doesn’t remove dependent ServiceDiscovery CRs: #754
* [x] At least with the Lighthouse upgrade test, it seems that one of the clusters is upgraded, but not the other
* [ ] Upgrading results in two sets of pods running in some circumstances, which causes problems: https://github.com/submariner-io/submariner/issues/1031

**Comment by nyechiel** [comment]
@skitt can you please update this one? Unless I am missing anything, we probably need to push it to 0.9 and discuss the broader topic of supporting upgrades, including documenting what we support.

**Comment by skitt** [comment]
#1031 isn’t done but it doesn’t cause issues in practice now that `subctl` handles upgrades properly. Upgrade tests are required on PRs where appropriate, and the project as a whole is aware that keeping upgrades working is important, so this epic no longer has a purpose.
